DROP TABLE IF EXISTS signatures;
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS users;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    first VARCHAR(200),
    last VARCHAR (200),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
